### ISSUE TITLE
Not working after update

### ISSUE THREAD

**Issue by MrBob101** [DusterTheFirst/FriendBot#1]
No channels are shown. I deleted and re authorized  bot but with no luck

**Comment by DusterTheFirst** [comment]
This will be repaired within the hour

**Comment by DusterTheFirst** [comment]
Bug has been fixed with patch 21,  was caused by moved files

**Comment by DusterTheFirst** [comment]
I am unable to understand your plroblem from the given message. 
Please include any __Stacktraces__ if available
And please tell me what __version__ of the plugin you have installed
And a step by step __instructions__ on how to __reproduce__ the problem
And any __other information__ you would like me to know
